// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnmNvVJ2r3YMAlBDN1ztZZK_NxiLiHqK8',
    appId: '1:297260001298:web:d0fe84adddaab64ed1d0cb',
    messagingSenderId: '297260001298',
    projectId: 'gr-ecommerce-school-project',
    authDomain: 'gr-ecommerce-school-project.firebaseapp.com',
    storageBucket: 'gr-ecommerce-school-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6jXQOhx__wymcBEPCcy5fKRT69CSsE5U',
    appId: '1:297260001298:android:de651c479b9b1edfd1d0cb',
    messagingSenderId: '297260001298',
    projectId: 'gr-ecommerce-school-project',
    storageBucket: 'gr-ecommerce-school-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRnk_r-HWAZmwgNPYQeqBQ4fbIEXUesvo',
    appId: '1:297260001298:ios:341e4378ff0fabfdd1d0cb',
    messagingSenderId: '297260001298',
    projectId: 'gr-ecommerce-school-project',
    storageBucket: 'gr-ecommerce-school-project.appspot.com',
    iosClientId: '297260001298-7va8okro4ifj9kcu4cp531qt1qd93qdf.apps.googleusercontent.com',
    iosBundleId: 'com.furqan.flutterEcommerceUiKit',
  );
}
